# Generated by Django 5.2 on 2025-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('produccion', 'Producción'), ('almacen', 'Almacén'), ('oficina', 'Oficina'), ('despachos', 'Despachos')], default='oficina', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contrato',
            field=models.CharField(choices=[('fijo', 'Término Fijo'), ('indefinido', 'Término Indefinido')], default='fijo', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('operario_auxiliar', 'Operario Auxiliar'), ('administrativo', 'Administrativo')], default='administrativo', max_length=50),
        ),
    ]
