# Generated by Django 5.2 on 2025-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_contact_alter_empleado_area_alter_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('ti', 'Tarjeta de Identidad'), ('pasaporte', 'Pasaporte')], default='cc', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ausentismo',
            table='rrhh_ausentismo',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='rrhh_contact',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='rrhh_empleado',
        ),
        migrations.AlterModelTable(
            name='horaextra',
            table='rrhh_hora_extra',
        ),
        migrations.AlterModelTable(
            name='nomina',
            table='rrhh_nomina',
        ),
    ]
