# Generated by Django 5.2 on 2025-05-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_contact_alter_empleado_area_alter_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ausentismo',
            table='rrhh_ausentismo',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='rrhh_contact',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='rrhh_empleado',
        ),
        migrations.AlterModelTable(
            name='horaextra',
            table='rrhh_hora_extra',
        ),
        migrations.AlterModelTable(
            name='nomina',
            table='rrhh_nomina',
        ),
    ]
