# Generated by Django 5.2 on 2025-05-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_alter_ausentismo_table_alter_contact_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('ti', 'Tarjeta de Identidad'), ('pasaporte', 'Pasaporte')], default='cc', max_length=20),
            preserve_default=False,
        ),
    ]
