# Generated by Django 5.2 on 2025-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_empleado_contacto_empleado_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(default='00000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
