# Generated by Django 5.2 on 2025-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0005_alter_ausentismo_motivo_alter_empleado_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_nombre', models.CharField(max_length=100)),
                ('contrato', models.CharField(max_length=50)),
                ('fondo_pensiones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caja_compensacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
