# Generated by Django 5.2 on 2025-05-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='horas_ausente',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_diurnas_festivas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extra_diurnas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extra_nocturnas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extras_diurnas_festivas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extras_nocturnas_festivas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_nocturnas_festivas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='recargos_nocturnos',
            field=models.FloatField(default=0),
        ),
    ]
