# Generated by Django 5.2 on 2025-05-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_add_documento_to_ausentismo'),
        ('recursos_humanos', '0007_nomina_horas_ausente_nomina_horas_diurnas_festivas_and_more'),
    ]

    operations = [
    ]
