# Generated by Django 5.2 on 2025-05-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0008_merge_20250516_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='tipo',
            field=models.CharField(choices=[('ausentismo', 'Ausentismo'), ('horas_extras', 'Horas Extras')], default='ausentismo', max_length=20),
        ),
    ]
