# Generated by Django 5.2 on 2025-05-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0009_ausentismo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horaextra',
            old_name='horas',
            new_name='duracion_horas',
        ),
        migrations.AddField(
            model_name='horaextra',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horas_extra_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horas_extra_dominicales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horas_extra_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='recargos_nocturnos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
