# Generated by Django 5.1.6 on 2025-05-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0010_rename_horas_horaextra_duracion_horas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausentismo',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='horas_extra_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='horas_extra_dominicales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='horas_extra_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ausentismo',
            name='recargos_nocturnos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
