# Generated by Django 5.1.6 on 2025-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_alter_ausentismo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=20),
        ),
    ]
