# Generated by Django 5.1.6 on 2025-05-18 22:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_empleado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='recursos_humanos.empleado'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='fecha_liquidacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='motivo_retiro',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
