# Generated by Django 5.1.6 on 2025-05-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0013_liquidacion_empleado_liquidacion_fecha_liquidacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='indemnizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='intereses_cesantias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='prima_servicios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='vacaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='caja_compensacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='cesantias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fondo_pensiones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
