# Generated by Django 5.2 on 2025-04-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
    ]
