# Generated by Django 5.2 on 2025-05-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
