# Generated by Django 5.2 on 2025-05-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_delete_cliente_alter_proveedor_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
