# Generated by Django 5.2 on 2025-05-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_delete_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salario_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.empleado')),
            ],
        ),
    ]
