# Generated by Django 5.1.6 on 2025-05-17 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_empleado_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='salario_neto',
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomina',
            name='tipo_periodo',
            field=models.CharField(default='Quincenal', max_length=50),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='bonificaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='deducciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
