# Generated by Django 5.1.6 on 2025-04-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
