# Generated by Django 5.2 on 2025-04-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_delete_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='preferencias',
            field=models.CharField(blank=True, default='Sin preferencias', max_length=200),
        ),
    ]
