# Generated by Django 5.2 on 2025-05-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_contacto_alter_cliente_preferencias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
