# Generated by Django 5.1.6 on 2025-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='evaluacion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='Sin direccion', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='Sin dirección', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
    ]
