# Generated by Django 5.1.6 on 2025-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200),
        ),
    ]
