# Generated by Django 5.2 on 2025-05-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_created_at_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
    ]
